name: Publish Image
on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
    - main
    tags:
    - v*
  workflow_dispatch: {}

env:
  DUPLO_HOST: ${{ vars.DUPLO_HOST }}
  DUPLO_TENANT: ${{ vars.DUPLO_TENANT }}
  DUPLO_TOKEN: "${{ secrets.DUPLO_TOKEN }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    - name: Build and Push Docker Image
      uses: duplocloud/actions/build-image@main
      with:
        platforms: linux/amd64,linux/arm64
        push: false