name: Build nad Publish Images
on:
  workflow_dispatch: {}
  workflow_call: 
    outputs:
      image:
        description: The URI of the image
        value: ${{ jobs.build_image.outputs.image }}
    secrets:
      DUPLO_TOKEN:
        description: The token to use for Duplo API calls
        required: true

env:
  DUPLO_HOST: ${{ secrets.DUPLO_HOST }}
  DUPLO_TENANT: ${{ secrets.DUPLO_TENANT }}
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}


jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    outputs:
      image: ${{ steps.build_image.outputs.uri }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    - name: Build and Push Frontend Docker Image
      id: build_image
      uses: duplocloud/actions/build-image@main
      with:
        platforms: linux/amd64
        push: true
        registry: "813590939111.dkr.ecr.us-west-2.amazonaws.com"
        repo: "frontend"
        build-args: >
          name=${{ github.repository }}

    - name: Build and Push Serverless Docker Image
      id: build_serverless_image
      uses: duplocloud/actions/build-image@main
      with:
        platforms: linux/amd64
        push: true
        registry: "813590939111.dkr.ecr.us-west-2.amazonaws.com"
        repo: "serverless"
        context: "lambda/"
        build-args: >
          name=${{ github.repository }}