name: Check Main

on:
  workflow_dispatch: {}

jobs:

  image:
    name: Main
    secrets: inherit
    uses: ./.github/workflows/image.yml

  deploy:
    name: Main
    uses: ./.github/workflows/deploy.yml
    needs: image
    secrets: inherit
    with:
      image: ${{ needs.image.outputs.image }}
      environment: qa-aws
